### ISSUE TITLE
Release the program?

### ISSUE THREAD

**Issue by The-Beesh-Spweesh** [tEFFx/oscigen#1]
How many channels can be shown at once? Does it have a GUI, or is it command-line?

**Comment by tEFFx** [comment]
At the moment it can only show waveforms in vertical order, so it could get tight if you'd want to have a lot of channels. I've tried 4 channels so far, but there should be space for at least 8 with decent clarity. It's command-line only at the moment.

I'll have to look into a Windows-build as it pipes the frame data to ffmpeg which is expected in the system folder. For Linux on the other hand it should just build as long as you have libSFML-dev and ffmpeg installet.

**Comment by The-Beesh-Spweesh** [comment]
@tEFFx I want a GUI, it's much better than command-line. I don't know how to use command-line programs anyways, as I'm not interested. SnoozeTracker, one of your other projects, has an interface.
